
services:

  postgres:
    image: postgres:17.6
    container_name: ums-postgres

    ports:
      - "5433:5433"

    volumes:
      - ums_postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: ums_identity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ums_identity_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: ums-keycloak

    ports:
      - "8088:8080"

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ums_identity_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: admin
      KC_DB_SCHEMA: public

    command:
      - start-dev

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  ums_postgres_data: